# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapMd
                                 A QGIS plugin
 This plugin uses Map.md API.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-21
        copyright            : (C) 2019 by Victor Pogor
        email                : victor.pogor@outlook.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapMd class from file MapMd.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_md import MapMd
    return MapMd(iface)
