# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapMd Utility Methods
                                 A QGIS plugin
 This plugin uses Map.md API.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-21
        git sha              : $Format:%H$
        copyright            : (C) 2019 by Victor Pogor
        email                : victor.pogor@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import csv


from qgis.utils import iface # pylint: disable=import-error

def read_csv(filename):
    """ Read CSV file. """
    try:
        with open(filename, 'r', encoding='utf-8') as csvfile:
            # Identify CSV dialect (delimiter)
            dialect = csv.Sniffer().sniff(csvfile.read(4096))
            csvfile.seek(0)
            reader = csv.reader(csvfile, dialect)

            for row in reader:
                yield row
    except IOError:
        iface.messageBar().pushCritical(
            "Input CSV File",
            "Failure opening " + filename)
    except UnicodeDecodeError:
        iface.messageBar().pushCritical(
            "Input CSV File",
            "Bad CSV file - Unicode decode error")
    except csv.Error:
        iface.messageBar().pushCritical(
            "Input CSV File",
            "Bad CSV file - verify that your delimiters are consistent")
